framework:
  messenger:
    failure_transport: failed
    transports:
      async:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        retry_strategy:
          delay: 500
        options:
          exchange:
            name: messages
            type: fanout
            default_publish_routing_key: normal
          queues:
            messages_normal:
              binding_keys: [normal]
      failed: 'doctrine://default?queue_name=failed'