services:
  rabbitmq:
    container_name: "rabbitmq"
    restart: always
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  mysql:
    container_name: "db"
    image: mysql:latest
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
      - "33060:33060"
    networks:
      - app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 2

  server:
    container_name: ${APP_NAME}
    restart: always
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/api
    working_dir: /api
    entrypoint: ["php", "-S", "0.0.0.0:8000", "-t", "/api/public/"]
    networks:
      - app

  consumer:
    container_name: ${APP_NAME}_consumer
    restart: always
    build: .
    env_file: .env
    volumes:
      - .:/api
    working_dir: /api
    command: "bin/console messenger:consume async"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - app

networks:
  app:
    driver: bridge